import '@repo/styles/globals.css';
import React from 'react';
import { Inter } from 'next/font/google';
import type { Metadata } from 'next';
import { ProvidersWrapper } from '@/components/ProvidersWrapper.tsx';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ProvidersWrapper>{children}</ProvidersWrapper>
      </body>
    </html>
  );
}

export default RootLayout;
